# Generated by Django 5.2.5 on 2025-08-28 04:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='사진')),
                ('thumbnail', models.ImageField(blank=True, editable=False, upload_to='thumbnails/%Y/%m/%d/', verbose_name='썸네일')),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='설명')),
                ('photo_date', models.DateField(default=datetime.date.today, verbose_name='촬영일')),
                ('category', models.CharField(choices=[('daily', '일상'), ('food', '음식'), ('travel', '여행'), ('people', '사람'), ('nature', '자연'), ('other', '기타')], default='daily', max_length=10, verbose_name='카테고리')),
                ('is_public', models.BooleanField(default=True, verbose_name='공개')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='업로드일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_photos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '일일 사진',
                'verbose_name_plural': '일일 사진들',
                'ordering': ['-photo_date', '-created_at'],
            },
        ),
    ]
